project:
  type: website
  output-dir: out
  render:
    - analysis/preprocess.qmd
    - map/index.qmd
  resources:
    - /data/3-pngs/*.png
    - data/map-bounds-extent.csv
  
# only re-render if the source changes or if we specifically render that file
execute:
  freeze: auto
